spring:
  profiles:
    active: simple
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/uniqwrites}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-client-secret}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email,profile
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@uniqwrites.com}
    password: ${MAIL_PASSWORD:dummy-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

firebase:
  config-path: ${FIREBASE_CONFIG_PATH}

app:
  upload:
    dir: ${UPLOAD_DIR:${user.home}/uniqwrites/uploads}
