# Simple development configuration with hard-coded values
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniqwrites_backend
    username: samson
    password: Secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Uniqwrites Web client
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email,profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: uniqwrites1@gmail.com
    password: qbhp pfsr apzt xdhb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: H6EAb5qdRWZuV5ZsXcTLj0CZUuRpCJ9smZfvwkEQ3sFC1I1y2RxnV2KXpgF5AJCCo1HFgxMznfFM40QgTWVv4Q==
  expirationMs: 3600000

firebase:
  config-path: classpath:firebase-service-account.json

app:
  upload:
    dir: C:/Users/Uniqwrites/uniqwrites1/uniqwrites-backend/uploads
